application:
  environment: production
  name: Production Demo
  version: 1.0.0
data:
  input_files:
  - data1.txt
  - data2.txt
  output_format: json
  processing_delay: 2
files:
  backup_original: true
  move_to_desktop: true
